services:
  postgres_tracker:
    image: postgres:latest
    container_name: postgres_tracker
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin_tracker:
    image: dpage/pgadmin4
    container_name: pgadmin_tracker
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

